In [34]:
import numpy as np

In [35]:

print("Task 1: Creating Arrays")
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.zeros(4)
arr3 = np.random.randint(1, 11, size=(2, 3))
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)
print("\n")

Task 1: Creating Arrays
Array 1: [1 2 3 4 5]
Array 2: [0. 0. 0. 0.]
Array 3: [[ 8  8 10]
 [ 2 10 10]]




In [36]:
#  Task: Perform basic array operations:- Add 5 to every element in arr1- Multiply arr1 by 2- 
# Calculate the square of each element in arr1

In [30]:
arr1_plus_5 = arr1 + 5
arr1_times_2 = arr1 * 2
arr1_squared = arr1 ** 2
print("Original array:", arr1)
print("Add 5:", arr1_plus_5)
print("Multiply by 2:", arr1_times_2)
print("Squared:", arr1_squared)
print("\n")

Original array: [1 2 3 4 5]
Add 5: [ 6  7  8  9 10]
Multiply by 2: [ 2  4  6  8 10]
Squared: [ 1  4  9 16 25]




In [31]:
#  Task: Create a 1D array with numbers 0-9 and:- Get the first 3 elements- 
#  Get all elements from index 5 onwards- Get every second element


In [32]:
arr4 = np.arange(10)
first_three = arr4[:3]
after_five = arr4[5:]
every_second = arr4[::2]
print(arr4[1:4:2])
print("Original array:", arr4)
print("First three:", first_three)
print("After index 5:", after_five)
print("Every second element:",every_second)
print("\n")

[1 3]
Original array: [0 1 2 3 4 5 6 7 8 9]
First three: [0 1 2]
After index 5: [5 6 7 8 9]
Every second element: [0 2 4 6 8]




In [33]:
'''Task: Create an array of numbers 1-12 and:- Reshape it into a 3x4 matrix- 
Reshape it into a 4x3 matrix- Transpose the 3x4 matrix'''

'Task: Create an array of numbers 1-12 and:- Reshape it into a 3x4 matrix- \nReshape it into a 4x3 matrix- Transpose the 3x4 matrix'

In [37]:
arr5 = np.arange(1, 13)
matrix_3x4 = arr5.reshape(3, 4)
matrix_4x3 = arr5.reshape(4, 3)
transposed = matrix_3x4.T
print("Original array:", arr5)
print("3x4 matrix:\n", matrix_3x4)
print("4x3 matrix:\n", matrix_4x3)
print("Transposed 3x4 matrix:\n", transposed)
print("\n")

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3 matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Transposed 3x4 matrix:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]




In [38]:
#  Task: Using the 3x4 matrix from Task 4:- Calculate the mean of all elements- Find the maximum value in each row-
#  Calculate the sum of each col

In [39]:
mean_value = np.mean(matrix_3x4)
row_max = np.max(matrix_3x4, axis=1)
col_sum = np.sum(matrix_3x4, axis=0)
print("3x4 matrix:\n", matrix_3x4)
print("Mean value:", mean_value)
print("Maximum values per row:", row_max)
print("Sum of each column:", col_sum)
print("\n")

3x4 matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Mean value: 6.5
Maximum values per row: [ 4  8 12]
Sum of each column: [15 18 21 24]




In [40]:
# k: Create an array of temperatures (in Celsius) and:- Find all temperatures above 25°C- 
# Replace all temperatures above 30°C with 30

In [41]:
temperatures = np.array([20, 25, 28, 32, 35, 27, 22, 31])
high_temps = temperatures[temperatures > 25]
temperatures_capped = np.clip(temperatures, None, 30)
print("Original temperatures:", temperatures)
print("Temperatures above 25°C:", high_temps)
print("Temperatures capped at 30°C:", temperatures_capped)
print("\n")

Original temperatures: [20 25 28 32 35 27 22 31]
Temperatures above 25°C: [28 32 35 27 31]
Temperatures capped at 30°C: [20 25 28 30 30 27 22 30]




In [42]:
#  Task: Create two 2x2 matrices and:- Add them together- Multiply them together (matrix multiplication)- 
#  Calculate the determinant of the first matrix

In [43]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
matrix_sum = matrix1 + matrix2
matrix_product = np.dot(matrix1, matrix2)
determinant = np.linalg.det(matrix1)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Sum of matrices:\n", matrix_sum)
print("Matrix product:\n", matrix_product)
print("Determinant of matrix 1:", determinant)
print("\n")

Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]
Sum of matrices:
 [[ 6  8]
 [10 12]]
Matrix product:
 [[19 22]
 [43 50]]
Determinant of matrix 1: -2.0000000000000004




In [44]:
''' """
 Task: Create two 1D arrays and:- Concatenate them horizontally- 
 Concatenate them vertically- Split the concatenated array into 3 equal parts'''


' """\n Task: Create two 1D arrays and:- Concatenate them horizontally- \n Concatenate them vertically- Split the concatenated array into 3 equal parts'

In [45]:
arr6 = np.array([1, 2, 3])
arr7 = np.array([4, 5, 6])
horizontal_concat = np.hstack((arr6, arr7))
vertical_concat = np.vstack((arr6, arr7))
split_array = np.array_split(horizontal_concat, 3)
print("Array 1:", arr6)
print("Array 2:", arr7)
print("Horizontal concatenation:", horizontal_concat)
print("Vertical concatenation:\n", vertical_concat)
print("Split into 3 parts:", split_array)
print("\n")

Array 1: [1 2 3]
Array 2: [4 5 6]
Horizontal concatenation: [1 2 3 4 5 6]
Vertical concatenation:
 [[1 2 3]
 [4 5 6]]
Split into 3 parts: [array([1, 2]), array([3, 4]), array([5, 6])]




In [46]:
# Task: Create a 3x3 matrix and:- 
# Add a scalar to all elements- Multiply each row by a different number

In [50]:
matrix3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
scalar_add = matrix3 + 10
row_multipliers = np.array([1, 2, 3]).reshape(-1, 1)
print(row_multipliers)
row_multiply = matrix3 * row_multipliers
print("Original matrix:\n", matrix3)
print("After adding 10:\n", scalar_add)
print("After multiplying each row by [1,2,3]:\n", row_multiply)
print("\n")

[[1]
 [2]
 [3]]
Original matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After adding 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
After multiplying each row by [1,2,3]:
 [[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]




In [48]:
# Demonstrate random number generation:- Create an array of 5 random numbers between 0 and 1- 
# Generate 10 numbers from a normal distribution- 
# Create a 4x4 matrix of random integers between 1-100

In [49]:
np.random.seed(42)  # For reproducibility
random_uniform = np.random.random(5)
random_normal = np.random.normal(size=10)
random_matrix = np.random.randint(1, 101, size=(4, 4))
print("Random numbers between 0 and 1:", random_uniform)
print("Numbers from normal distribution:", random_normal)
print("4x4 random integer matrix:\n", random_matrix)

Random numbers between 0 and 1: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
Numbers from normal distribution: [ 0.27904129  1.01051528 -0.58087813 -0.52516981 -0.57138017 -0.92408284
 -2.61254901  0.95036968  0.81644508 -1.523876  ]
4x4 random integer matrix:
 [[42 92 60 80]
 [15 62 62 47]
 [62 51 55 64]
 [ 3 51  7 21]]
